//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempbre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists_Songs
    {
        public int ArtistID { get; set; }
        public int SongID { get; set; }
    }
}
