//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempbre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscoFishEntitiesBridges : DbContext
    {
        public DiscoFishEntitiesBridges()
            : base("name=DiscoFishEntitiesBridges")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Albums_Artists> Albums_Artists { get; set; }
        public virtual DbSet<Albums_Songs> Albums_Songs { get; set; }
        public virtual DbSet<Artists_Songs> Artists_Songs { get; set; }
    }
}
