//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tempbre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Albums = new HashSet<Album>();
            this.Artists = new HashSet<Artist>();
        }
    
        public int SongID { get; set; }
        public string Title { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public Nullable<int> TrackNumber { get; set; }
        public string Genre { get; set; }
        public string SubGenre { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsInstrumental { get; set; }
        public Nullable<bool> IsScore { get; set; }
        public Nullable<System.TimeSpan> Length { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Artist> Artists { get; set; }
    }
}
